"""Writers for processed data, report tables, metrics and markdown reports.

All outputs are written with fixed decimal formatting and slash separated
dates so that every generated artefact is free of scientific notation.
"""

import json
import math

import numpy as np
import pandas as pd

from . import config as cfg

CSV_OPTIONS = {"index": False, "float_format": "%.4f", "date_format": "%Y/%m/%d"}


def write_csv(frame, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, **CSV_OPTIONS)
    return path


def _sanitise(value):
    if isinstance(value, dict):
        return {str(k): _sanitise(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_sanitise(v) for v in value]
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (float, np.floating)):
        value = float(value)
        if math.isnan(value) or math.isinf(value):
            return None
        if value != 0 and abs(value) < 0.0001:
            return "below 0.0001"
        return round(value, 6)
    if isinstance(value, pd.Timestamp):
        return value.strftime("%Y/%m/%d")
    return value


def write_json(payload, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(_sanitise(payload), indent=2))
    return path


def fmt_p(p):
    if p is None or (isinstance(p, float) and math.isnan(p)):
        return "n/a"
    return "below 0.0001" if p < 0.0001 else f"{p:.4f}"


def html_table(frame, float_digits=2):
    """Render a DataFrame as a plain HTML table that GitHub renders cleanly."""
    def cell(value):
        if value is None or (isinstance(value, float) and math.isnan(value)):
            return ""
        if isinstance(value, (float, np.floating)):
            return f"{value:,.{float_digits}f}"
        if isinstance(value, (int, np.integer)) and not isinstance(value, bool):
            return f"{value:,}"
        return str(value)

    head = "".join(f"<th>{c}</th>" for c in frame.columns)
    body = "".join(
        "<tr>" + "".join(f"<td>{cell(v)}</td>" for v in row) + "</tr>"
        for row in frame.itertuples(index=False)
    )
    return f"<table>\n<thead><tr>{head}</tr></thead>\n<tbody>{body}</tbody>\n</table>\n"


def data_quality_report(raw_profile, log, clean_df, path):
    """Markdown report documenting every processing decision."""
    log_frame = log.to_frame()
    raw_rows = int(log_frame.loc[log_frame["issue"].eq("Raw export loaded"), "rows_affected"].iloc[0])
    lines = [
        "# Data Quality and Processing Report",
        "",
        "This report is generated by the pipeline. It documents the state of the raw export, "
        "every processing action taken, and the integrity checks applied before analysis.",
        "",
        "## Summary",
        "",
        f"The raw export contained {raw_rows:,} rows and {raw_profile.shape[0]} columns. "
        f"After processing, {len(clean_df):,} unique captures remain, keyed on capture_id. "
        f"{int((clean_df['data_issue_count'] > 0).sum()):,} captures carry at least one integrity flag, "
        "and every flag is preserved as a column so that no repair is invisible.",
        "",
        "## Raw column profile",
        "",
        html_table(raw_profile),
        "## Processing log",
        "",
        html_table(log_frame),
        "## Principles applied",
        "",
        "1. Evidential measurements (speed, confidence scores, image quality, latency) are never imputed. "
        "Invalid readings are nulled and flagged, because an imputed speed cannot support a citation.",
        "2. Descriptive categories receive an explicit Unknown level rather than a guessed value.",
        "3. Every repaired or contradictory field keeps its original value in a companion column.",
        "4. Ambiguous slash dates are resolved against the date window established by unambiguous "
        "records and otherwise default to month first, with a per row ambiguity flag.",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    return path


def analytics_report(results, path):
    """Markdown report of the core analytics, generated from the results bundle."""
    m = results["metrics"]
    wl = m["workload_and_value"]
    bench = m["overall_benchmark"]
    sens = m["limit_source_sensitivity"]
    appeals = m["citations_and_appeals"]
    model = m["false_positive_model"]
    tests = m["perception_tests"]

    lines = [
        "# Core Analytics Report",
        "",
        "Generated by the pipeline from the processed capture log.",
        "",
        "## 1. Rules layer decisions",
        "",
        html_table(results["decision_summary"].reset_index()),
        f"Evidence gates passed on {bench['evidence_gate_pass_pct']:.2f}% of captures. "
        f"Manual review workload is {wl['manual_review_cases']:,} cases, about {wl['manual_review_hours']:,.1f} "
        f"reviewer hours ({wl['manual_review_shifts']:,.1f} shifts) at {cfg.REVIEW_MINUTES_PER_CASE:g} minutes per case.",
        "",
        "## 2. Reconciliation with recorded labels",
        "",
        html_table(results["reconciliation"]),
        f"Speed limit sensitivity: the two limit fields disagree on {sens['limit_fields_disagree_pct']:.2f}% of captures "
        f"and the speeding decision agrees across them on only {sens['speeding_decision_agreement_pct']:.2f}% of captures. "
        f"Recorded speeding is supported by measured speed in {sens['recorded_speeding_supported_by_posted_limit_pct']:.2f}% "
        f"of cases using the posted limit and {sens['recorded_speeding_supported_by_segment_limit_pct']:.2f}% using the segment limit.",
        "",
        "## 3. Data integrity",
        "",
        html_table(results["label_integrity"]),
        "## 4. Perception stage scorecard",
        "",
        html_table(results["model_scorecard"], float_digits=3),
        f"False positive rate differs by model: chi square p value {fmt_p(tests['false_positive_rate_by_model']['p_value'])}, "
        f"Cramer V {tests['false_positive_rate_by_model']['cramers_v']}. "
        f"OCR confidence by lighting: Kruskal Wallis p value {fmt_p(tests['ocr_confidence_by_lighting']['p_value'])}. "
        f"OCR confidence by weather: p value {fmt_p(tests['ocr_confidence_by_weather']['p_value'])}.",
        "",
        "### False positive separability",
        "",
        html_table(results["separability"], float_digits=4),
        "### Threshold sweep (detection threshold 0.70)",
        "",
        html_table(results["threshold_sweep"][results["threshold_sweep"]["detection_threshold"].eq(0.7)]),
        "## 5. Benchmark",
        "",
        html_table(results["benchmark"]),
        f"Overall p95 latency {bench['latency_p95_ms']} ms (95% bootstrap interval {bench['latency_p95_ci_ms'][0]} to "
        f"{bench['latency_p95_ci_ms'][1]} ms); {bench['latency_sla_compliance_pct']:.2f}% of captures meet the "
        f"{cfg.LATENCY_SLA_MS:.0f} ms SLA.",
        "",
        "## 6. False positive triage model",
        "",
        html_table(results["model_results"], float_digits=4),
        f"Best model: {model['best_model']} with ROC AUC {model['best_roc_auc']:.4f}; permutation test p value "
        f"{model['permutation_p_value']:.4f} over {model['permutations']} permutations. Deployable: {model['deployable']}.",
        "",
        "## 7. Corridors",
        "",
        html_table(results["corridor_summary"]),
        "## 8. Citations and appeals",
        "",
        f"Citations recorded: {appeals['citations_recorded']:,}. Citations without a supported violation: "
        f"{appeals['citations_without_supported_violation']:,}. Appeals filed on citations: {appeals['appeals_filed_on_citations']:,} "
        f"(rate {appeals['appeal_rate_pct']}%). Decided appeals: {appeals['appeals_decided']}, overturned "
        f"{appeals['appeals_overturned']} ({appeals['overturn_rate_pct']}%).",
        "",
        "## 9. Privacy and retention",
        "",
        html_table(results["retention_summary"]),
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    return path
